model = dict(
    type='FasterRCNN',
    # pretrained='/media/p/research/experiment/NAS/DARTSImp/PC-DARTS/checkpoints/eval-try-20200522-124131/model_best.pth.tar',
    # pretrained='/media/p/research/experiment/NAS/DARTSImp/PC-DARTS/pretained/0608/model_best.pth.tar',
    # pretrained="/media/p/research/experiment/NAS/DARTSImp/PC-DARTS/pretained/0608_selected/model_best.pth.tar",
    # pretrained="/media/p/research/experiment/NAS/DARTSImp/PC-DARTS/checkpoints/eval-try-20200609-111058/checkpoint.pth.tar",
    # pretrained = "/media/p/research/experiment/NAS/DARTSImp/PC-DARTS/checkpoints/eval-try-20200609-111058/model_best.pth.tar",
    pretrained = "/media/p/research/experiment/NAS/DARTSImp/PC-DARTS/checkpoints/eval-try-20200609-235829/model_best.pth.tar",
    # pretrained=None,
    backbone=dict(
        type='NetworkImageNet',
        # C=48,
        C=96,
        num_classes=1,
        # layers=14,
        # layers=12,
	    # layers=16,
        layers=14,
        auxiliary=False),
    neck=dict(
        type='FPN',
        # in_channels=[256, 512, 1024, 2048],
        # in_channels=[48, 384, 768, 768],
        in_channels=[96, 768, 1536, 1536],
        # out_channels=48,
        # in_channels=[96, 768, 1536, 1536],
        out_channels=96,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        # in_channels=48,
        in_channels=96,
        feat_channels=96,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    roi_head=dict(
        type='StandardRoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', out_size=7, sample_num=0),
            out_channels=96,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=dict(
            type='Shared2FCBBoxHead',
            in_channels=96,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=1,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0., 0., 0., 0.],
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            reg_class_agnostic=False,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='L1Loss', loss_weight=1.0))))
# model training and testing settings
train_cfg = dict(
    rpn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.7,
            neg_iou_thr=0.3,
            min_pos_iou=0.3,
            match_low_quality=True,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=256,
            pos_fraction=0.5,
            neg_pos_ub=-1,
            add_gt_as_proposals=False),
        allowed_border=-1,
        pos_weight=-1,
        debug=False),
    rpn_proposal=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=1000,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0.5,
            match_low_quality=False,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=512,
            pos_fraction=0.25,
            neg_pos_ub=-1,
            add_gt_as_proposals=True),
        pos_weight=-1,
        debug=False))
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=1000,
        nms_post=1000,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.05, nms=dict(type='nms', iou_thr=0.5), max_per_img=100)
    # soft-nms is also supported for rcnn testing
    # e.g., nms=dict(type='soft_nms', iou_thr=0.5, min_score=0.05)
)
